### ISSUE TITLE
Font-Größe anpassen

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Layouts#10]
Die Font-Größe von `<h1>, <h2>, ...` herunterdrehen.

**Comment by cyildiz** [comment]
**Vorher**:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1532767/132751384-5f89b961-db57-4616-bc41-4573779b577e.png">

\ 


**Nachher** (font-size angepasst, alles linksbündig, margins nicht geändert):
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1532767/132751969-2ca00e9c-7b1f-4be2-b5d5-ddfa6ddf8960.png">

**Comment by cagix** [comment]
sieht gut aus 😀

**Comment by cyildiz** [comment]
Ich kann jetzt keine style-änderungen zum reviewen pushen, oder?

die styles sind innerhalb des layout-submodules definiert, das darf ich nicht pushen.

gibt es eine andere stelle, wo ich styles hinzufügen kann, die dann global gültig sind?
oder innerhalb einer bestimmten seite würde auch reichen.

**Comment by cagix** [comment]
hmmm? die style-sachen sind doch hier im custom-header.html, oder? da kannst du doch einen branch pushen?

**Comment by cagix** [comment]
also wie vorhin auch hier im layout-repo pushen ...

**Comment by cyildiz** [comment]
Hier kanns Du es dann aber nicht direkt sehen.
Ich dachte an die kitest-repo. 

Kann ich in der kitest repo nicht änderungen im layout-submodule pushen, solange ich auf einem separaten branch bin und dieser nie gemergt wird?

Wenn nicht, dann mache ich es hier wie gewohnt.

**Comment by cagix** [comment]
mach mal bitte hier, ich kann das ja dann manuell rüberziehen zum testen. das kitest hatte ich leider als erstes umgestellt (um die submodules zu testen), d.h. da geht es auch nicht :/ 

vielleicht waren die submodules doch keine so gute idee ...

**Comment by cyildiz** [comment]
Wie wäre es damit:
```
h1 { font-size:2.8em !important;}
h2 { font-size:2.2em; margin:1.2rem 0}
h3 { font-size:1.9em; text-align:left !important; font-weight:400 !important;}
h4 { font-size:1.6em}
h5 { font-size:1.3em}
h6 { font-size:1em}

h2{
    width:100% !important;
    border-bottom:1px solid #222222 !important;
    padding-bottom: 2px;
}
.assignments h2 {margin:0.5rem 0}
```

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/1532767/132854342-c1bfa984-5ba1-4b22-b0dd-37b2c188145c.png">

**Comment by cagix** [comment]
> Wie wäre es hiermit (bei Übungsblätter ist oben das margin kleiner):
> 
> ```
> 
> h1 { font-size:2.8em !important;}
> 
> h2 { font-size:2.2em; margin:1.2rem 0}
> 
> h3 { font-size:1.9em; text-align:left !important; font-weight:400 !important;}
> 
> h4 { font-size:1.6em}
> 
> h5 { font-size:1.3em}
> 
> h6 { font-size:1em}
> 
> 
> 
> h2{
> 
>     width:100% !important;
> 
>     border-bottom:1px solid #222222 !important;
> 
>     padding-bottom: 2px;
> 
> }
> 
> .assignments h2 {margin:0.5rem 0}
> 
> ```
> 
> 
> 
> <img width="1066" alt="image" src="https://user-images.githubusercontent.com/1532767/132854342-c1bfa984-5ba1-4b22-b0dd-37b2c188145c.png">
> 
> 

sieht gut aus 👍

das margin bei den übungsblättern finde ich super, kannst du das für die anderen special sections auch übernehmen?

**Comment by cagix** [comment]
closed in 0a96067 (#14)
