### ISSUE TITLE
Fahrplan - bug in Vorlesung Spalte?

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Layouts#18]
In der Lecture-repo, im branch `planning`, nachdem ich das layouts-submodule aktualisiert habe (auf den lezten commit `f050123`) sehe ich folgende issue:

misc_lecture -> notes wird nicht angezeigt, obwohl es existiert.
In KW43 wird z.B. nur ein `<br>` hinzugefügt, obwohl folgende notes eingetragen sind:
```
misc_lecture:
    - notes: "[KI, Carsten]: Spiele (Minimax, alpha-beta-Pruning, Heuristiken)"
```

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1532767/132944859-3b1ee0fc-20f2-4d40-a296-c86bfbf19504.png">

**Comment by cyildiz** [comment]
Seltsam...
Wenn ich bei KW43 eine eckige Klammer entferne, wird die Zeile plötzlich gerendert.
Dabei werden in KW42 die `[ .. ]` ohne Probleme angezeigt...

<img width="697" alt="image" src="https://user-images.githubusercontent.com/1532767/132947388-63e0c9e1-dc56-4342-be44-9150116326a3.png">

KW42:
`   - notes: "[KI, Carsten]: Lokale Suche (Gradientenabstieg, Simulated Annealing), Genetische Algorithmen"`
KW43:
`    - notes: "[KI, Carsten]: Spiele (Minimax, alpha-beta-Pruning, Heuristiken)"`

Ich sehe keinen Unterschied, außer dem `)"` am Ende des Textes..
Und tatsächlich scheint das der wunde Punkt zu sein...

**Comment by cagix** [comment]
ok, schaue ich mir bei gelegenheit an.

**Comment by cagix** [comment]
ich habe einen verdacht: ich lasse den kommentar von hugo als markdown interpretieren. dein schnipsel erinnert stark an einen link (ist technisch aber keiner), vielleicht geht da was schief. 

aber ich habe gestern auch noch einige dinge vereinfacht/vereinheitlicht, vielleicht ist dabei was schief gegangen...

**Comment by cagix** [comment]
@cyildiz Das ist tatsächlich ein Hugo-Bug :/  ... 

Wir haben zwei Möglichkeiten:
1. Wir nehmen das `| markdownify` im `schedule.html` raus, oder
2. Wir müssen Dinge bei Bedarf (wenn Hugo wie oben nicht damit klar kommt) anders schreiben

Bei (1) verzichten wir auf die Möglichkeit, den Kommentar (leicht) zu formatieren (fett, kursiv ...).
Bei (2) würde man immer noch sowas schreiben können: `-notes: "**Wichtig**: ..."`, aber man müsste das Ergbnis immer im Auge behalten und bei Bedarf den Parser von Hugo unterstützen, indem man die Note anders formuliert.

Ich tendiere zu (1). Was denkst Du?

**Comment by cagix** [comment]
@cyildiz das ist seltsam, in meinen tests hat genau das eigentlich gut funktioniert. aber es ist auch inkonsistent, nur die notes und nicht die anderen elemente zu bearbeiten. insofern sollte es mit option (1) vereinheitlicht werden :)
