### ISSUE TITLE
Layout: Unterstriche unter H2 etwas aufdringlich

### ISSUE THREAD

**Issue by cagix** [cagix/Hugo-Lecture-Layouts#19]
Aktuell werden alle H2-Überschriften extra mit einem Unterstrich versehen. In der Übersicht in #10 sah das eigentlich ganz gut aus, aber wenn ich mir jetzt eine ganze Vorlesung damit anschaue, finde ich die Unterstriche etwas aufdringlich:

<img width="876" alt="Screenshot 2021-09-11 at 16 41 04" src="https://user-images.githubusercontent.com/20356276/132951542-2691b855-62a1-419d-beeb-d0d72d1e528a.png">

Vorschlag: Könnten wir die Unterstriche doch wieder rausnehmen oder deutlich "durchsichtiger" machen?

---

PS: Wenn Du eine starke Präferenz für die Unterstriche hast, kann ich auch damit leben ;)

**Comment by cagix** [comment]
@cyildiz ich habe gerade die erste vorlesung damit gebaut und nehme meinen einwand direkt zurück. sieht mit text dazwischen doch richtig gut aus :)

**Comment by cyildiz** [comment]
Ich hatte die Linie `#222` statt `#000` gefärbt. Eventuell könnten wir es in Zukunft etwas heller färben, z.B. `#666`.

**Comment by cagix** [comment]
alles gut :)  ich hatte mir die leere webseite mit nur den dummy-überschriften angesehen, und da fand ich die unterstriche etwas viel. aber wenn man dann tatsächlich inhalte hat, passt es wieder und sieht sehr gut aus. ich würde es jetzt erstmal so lassen.
