### ISSUE TITLE
Schedule - Leerraum in Zelle reduzieren

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Layouts#2]
In der Schedule/Fahrplan Tabelle den Leerraum um die \<ul> Elemente (margin bzw. padding) innerhalb der Zellen reduzieren.

Vorschlag:
`
td ul, td ol {
        margin: 0.5rem 0;
        padding: 0 0.5rem;
    }
`

**Comment by cagix** [comment]
Finde ich gut :)

Langfristig sollten wir überlegen, ob wir uns nochmal auf die Suche nach einem anderen Template machen oder mein altes Pandoc-Template übertragen. Das Hugo-Learn-Theme ist mir zu "pompös". Aber die Studis, die das ausgesucht hatten, mochten es vor allen schlankeren Themes ...

**Comment by cagix** [comment]
@cyildiz GitHub sieht irgendwie einen Commit, kann den aber nicht zuordnen und beim Fetch/Pull kommt er auch nicht mit runter. Bevor das jetzt noch verloren geht, kannst Du bitte vom Master aus einen Branch anlegen und dort den Commit mit `git cherry-pick e2f4b4b` retten und den Branch hier pushen + einen PR anlegen?

<img width="1009" alt="Screenshot 2021-09-09 at 09 40 49" src="https://user-images.githubusercontent.com/20356276/132643887-92bca527-a389-47d0-8a45-c2b655762f8b.png">

**Comment by cyildiz** [comment]
Ich habe das etwas falsch gemacht im iusse-2 glaube ich :(
Ich habe vor dem pushen lokal ein commit --amend gemacht.

Lokal sieht es bei mir jetzt so aus:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/1532767/132646954-5f81886a-7e41-4c41-abbb-addd17219598.png">

**Comment by cyildiz** [comment]
Ich habe diese branch eben noch ein mal gepusht.
Könntest Du es Dir bitte kurz ansehen bevor ich PR anlege?

**Comment by cyildiz** [comment]
Sorry, ich musste gitk neu starten, um den letzten Stand zu sehen.
Habe ich jetzt doch noch etwas kaputt gemacht:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/1532767/132649628-cba55258-15c5-474a-b5a7-2e94fe981093.png">

**Comment by cagix** [comment]
ah, jetzt verstehe ich das :)  ich hatte den pull-request, der mit dem branch `issue-2` verknüpft war, gemergt und dabei wird der branch gelöscht. d.h. der commit hing in der luft.

es gibt zwei optionen: entweder du legst einen neuen feature-branch für dieses ticket an und macht einen cherry-pick auf den einen commit. oder du legst einen pr für deinen `issue-2`-branch an, wie er jetzt ist und ich mache den cherry-pick.

**Comment by cagix** [comment]
ähm, das neue bild sieht doch gut aus? mache einfach folgendes: `git checkout master && git pull && git rebase --onto master issue-3 issue-2 && git push -f origin issue-2". dann passt doch alles?

**Comment by cagix** [comment]
@cyildiz sieht gut aus :)

Eine Frage noch: Das greift jetzt alle Tabellen, also nicht nur den Schedule. Sollen wir das beschränken auf den Schedule oder passt das auch bei anderen Tabellen (also auf unseren Pages)?

**Comment by cyildiz** [comment]
Super, danke!
War dabei, mit falschen git-Befehlen herumzugekämpfen :\

Die Listenelemente waren zu sehr eingerückt in der Zelle, das würde ich eigentlich in allen Tabellen ändern, wenn der Abstand links jetzt nicht zu klein ist.

**Comment by cagix** [comment]
ich denke, das passt 👍  ich wollte nur nochmal sichergehen, ob wir das auf alle tabellen ausrollen wollen.

ok, dann merge ich das jetzt :)

mittel-/langfristig sollten wir echt über ein eigenes theme nachdenken. im learn-theme ist soviel kram drin, den wir nicht brauchen, und das ding braucht echt viel platz auf dem bildschirm.

**Comment by cagix** [comment]
uff, nach links ist das doch recht knapp, oder? jedenfalls für die stichpunkte finde ich das etwas zu eng. 

siehst du da einen workaround, der das evtl. nur für die linke seite und nur die aufzählungen etwas großzügiger gestaltet?

dafür könnte oben und unten noch etwas platz rausgenommen werden ... 

<img width="1009" alt="Screenshot 2021-09-09 at 11 56 59" src="https://user-images.githubusercontent.com/20356276/132665337-e3e44dbe-dd1e-40ad-8751-fd84eed98196.png">

**Comment by cyildiz** [comment]
Wie wäre es so:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/1532767/132666431-a432bb3a-460e-4f52-8566-650f384b5329.png">

**Comment by cagix** [comment]
ja, das ist besser :) 

kriegst du den space oben und unter der Aufzählung noch etwas kleiner? Ist das ein Padding in der Table-Cell oder in der Aufzählung?

**Comment by cyildiz** [comment]
Hier gibt es jetzt nur das default-padding von `<td>`  (0.5em):

<img width="596" alt="image" src="https://user-images.githubusercontent.com/1532767/132668399-f797dd80-1d72-40f2-933f-94155366cce8.png">

**Comment by cagix** [comment]
okay, das könnten wir jetzt so nehmen. aktualisierst du bitte den pr nochmal?

**Comment by cyildiz** [comment]
Done.

**Comment by cagix** [comment]
closed by 645049d
