### ISSUE TITLE
Lernziele nur aneigen, falls outcomes definiert sind.

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Layouts#20]
Im Moment wird die Lernziele-section gerendert, auch wenn die Datei outcomes.md nicht existiert.

`{{ $outcomes := .Resources.Match "outcomes.md" }}`
sollte in dem Fall eigentlich `false` zurückliefern, oder?

**Comment by cyildiz** [comment]
Sorry, das Problem liegt woanders.

Ich habe `markdown/xyz/outcomes.md` gelöscht und `make web` ausgeführt.
Dabei wurde aber `content/xyz/outcomes.md` nicht gelöscht.

@cagix , wie könnte/sollte ich diese Änderung unter `markdown/` in den `content/` folder übertragen?

**Comment by cagix** [comment]
@cyildiz Make kopiert alle Dateien von `markdown/` nach `content/`,  um dort dann "ungestört" die weitere Verarbeitung machen zu können, insbesondere damit dann Git nicht immer über Änderungen meckert.

Dabei werden nur Dateien in `content/` überschrieben, die auch gleichnamig in `markdown/` sind. 

Du kannst einfach ein `make clean` machen, und der Inhalt von `content/` wird entfernt. Beim nächsten `make web` wird dann sowieso wieder alles kopiert.

**Comment by cagix** [comment]
Alternativ kannst Du natürlich auch direkt in `content/` was löschen/editieren. Ich vermeide das, weil ich schon stundenlang auf der Suche nach einem Fehler war und am Ende gemerkt hatte, dass ich im falschen Ordner editiert hatte :/

**Comment by cagix** [comment]
Ich hatte auch schon überlegt, dem `make web` automatisch ein `make clean` vorzuschalten. Aber dann werden alle Vorverarbeitungsschritte bei jedem `make web` komplett erneut ausgeführt. Hmmm.
