### ISSUE TITLE
Fahrplan/Schedule: Wochespalte editieren

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Layouts#3]
- Spalten-Header ist als "Woche" beschriftet, in den Zellen darunter könnte man daher den Text "Woche" weglassen (um Lesbarkeit zu erhöhen und Spaltenbreite zu reduzieren).
- Ein Zeilenumbruch vor (KWxx) würde die Spaltenbreite weiter reduzieren.

**Comment by cagix** [comment]
Den ersten Punkt finde ich gut, das ist redundant. Man könnte sogar überlegen, ob man die Vorlesungswoche gleich ganz weglässt und nur mit den KW-Informationen aus dem Schedule arbeitet? @cyildiz Was denkst Du?

---

Einen Zeilenumbruch finde ich schwierig. Das würde bei breiten Monitoren die einzeilige Darstellung verhindern, und auf noch kleineren Monitoren (Handy) hat man zusätzlich noch einen harten Umbruch (da bricht ja die Zelle in sich um, aber zusätzlich hätte man dann noch den Umbruch zw. Woche und KW)?

**Comment by cagix** [comment]
aber letztlich kann ich auch mit einem zeilenumbruch gut leben :)

**Comment by cyildiz** [comment]
Wen man die Wochenzahl (1, 2, ...) weglässt, könnte man die Spalte mit "KW" bezeichnen und dann nur die KW-Zahl schreiben (40, 41, ...).
Aber die Wochenzahl sagt eigentlich auch was aus (relativ zum Semesterbeginn), daher würde ich es eher nicht weglassen.

Bei breiten Monitoren wird zweizeilig dargestellt, aber;
- weil die Zeilen sowieso hoch sind, hat das keinen Einfluss auf den vertikal genutzten Platz,
- die zweite Spalte kann auch bei breiten Monitoren etwas extra Platz gebrauchen,
- sehr schlecht sieht es auch nicht aus  (oder?) :)

**Comment by cagix** [comment]
ja, ich finde die relative wochenzahl eigentlich auch gut, gerade aus sicht der studis. die rechnen eher nicht in kw :)

lass uns das mit dem umbruch einfach machen. bist du an den pr's oder kann ich das rasch fixen?

**Comment by cyildiz** [comment]
Ich habe diese Repo noch nicht geklont, die Änderungen habe ich in der anderen Repo ausprobiert.
Bei mir würde es noch etwas dauern. 
Wenn Du möchtest, sage ich nicht Nein :)
