### ISSUE TITLE
Fahrplan/Schedule: zwei Anzeigeoptionen für misc-Info

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Layouts#4]
Zwei Mögliche Layouts für die misc-Informationen:

- als zusätzliche Spalte und/oder
- als neue Zeile am Ende der Topic-Liste in der Vorlesung-Spalte

Könnte man mit einer zusätzlichen Boolean-Variable regeln:
- **$ifmisc_col = True**  => als Spalte anzeigen, wenn vorhanden
- **$ifmisc = True**   => in Vorlesung-Spalte anzeigen, wenn vorhanden

**Comment by cagix** [comment]
@cyildiz Im Moment wird die Spalte nur angezeigt, wenn ich auch mind. ein "misc" konfiguriere, also kein "misc" im Schedule == keine (leere) Spalte. Gibt es eine Situation, wo wir ein "misc" haben und dann diese Konfiguration brauchen? 

Wenn wir das so umsetzen wollen, würde ich nur eine neue Variable einführen, vielleicht `misc_col = true` => zeige eine extra Spalte an, sofern es mind. ein "misc"-Eintrag gibt und `misc_col = false` => setze eventuelle "misc"-Einträge in das Ende der jeweiligen VL-Zelle.

Ich bin grad am überlegen, ob man diese Variable tatsächlich im YAML-File (`schedule.yaml`) setzen will? Das würde bedeuten, dass man die wochenweise setzen kann, was wieder andere lustige Effekte hervorrufen kann. 

Alternativ wäre das vielleicht eine Sache für die globale Konfiguration, was mir im Moment am saubersten erscheint. Nachteil wäre dabei, dass die Konfiguration mental recht weit entfernt vom Schedule ist. Aber andererseits bestimmt man das genaue Aussehen des Schedules ja auch wieder durch einen Shortcode, der quasi "irgendwo" herumliegt.

Was denkst Du?

**Comment by cyildiz** [comment]
Im Moment kann man ja per Topic einen Hinweis hinzufügen (notes).
Dieses misc wäre eine Art Hinweis für die ganze Woche.

Vielleicht kann man diese Dinge separieren:
- möchte man eine extra Spalte, nutzt man `misc` unter `lecture`,
- möchte man einen Hinweis für die Woche (unter die `<ul>` Elemente), nutzt man einen `notes` unter `lecture`.

Was meinst Du?

**Comment by cagix** [comment]
> Im Moment kann man ja per Topic einen Hinweis hinzufügen (notes).
> Dieses misc wäre eine Art Hinweis für die ganze Woche.

genau. die frage ist nur, wo dieses "misc" erscheinen soll: mit in der vl-spalte oder in einer eigenen spalte?

> * möchte man eine extra Spalte, nutzt man `misc` unter `lecture`,

so ist es aktuell implementiert.

> * möchte man einen Hinweis für die Woche (unter die `<ul>` Elemente), nutzt man einen `notes` unter `lecture`.

hmmm, das würde den neuen schalter sparen. das wäre gar nicht so schlecht :)

**Comment by cagix** [comment]
zwei keys: `misc_lecture`und `misc_column`, ersteres unter den topic, letzteres in eigener spalte ... als markdown interpretieren (formatierung erlauben)

**Comment by cagix** [comment]
```markdown
---
- week: "KW40"
  lecture:
    - topic: "/misc/syllabus"
  misc_lecture:
    - notes: "WICHTIG: Durchgeführt von **Canan**"
    - page: "/misc/resources"
      notes: "Vortrag Thema I"
    - page: "/misc/schedule"
    - notes: "Durchgeführt von Canan"
  misc_column:
    - page: "/misc/resources"
      notes: "Vortrag Thema I"
    - notes: "Coden mit Edmonton"
    - page: "/misc/schedule"

- week: "KW41"
  lecture:
    - topic: "/misc/syllabus"
    - topic: "/misc/syllabus"
      notes: "Bemerkung"
  assignment:
    - topic: "sheet01"
      due: "14.10."
---
```
