### ISSUE TITLE
Fahrplan/Schedule: zwei Variationen für Leader-Info

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Layouts#5]
Bei manchen LVen gibt es einen leader pro KW, bei anderen wird innerhalb einer KW gewechselt.

Vorschlag von Carsten: zusätliche Variable im header:
```
- week: "KW40"
  lecture:
    - topic: "/misc/syllabus"
      leader: "Leader für diese Lesson, geht in die VL-Spalte zur Lesson"
  leader: "gemeinsamer Leader, geht in die Wochen-Spalte"
  misc:
    - page: "/misc/resources"
      notes: "Vortrag Thema I"
    - notes: "Coden mit Edmonton"
    - page: "/misc/schedule"
```

- Wenn leader unter topic gesetzt ist, wird es angezeigt, sonst fällt es weg.
- Wenn leader unter lecture gesezt ist, könnte es
   -  in der Woche-Spalte, oder 
   - am Ende der Vorlesung-Spalte angezeigt werden.

@cagix , was meinst Du?

**Comment by cagix** [comment]
@cyildiz Wenn der "leader" in der Woche gesetzt ist, würde ich das dann eher am Ende der Vorlesungs-Zelle anzeigen. Also die ganzen Sitzungen mit Links als Stichpunkt-Liste, und darunter dann den Leader-Text der jeweiligen Woche.

Wenn ich das (wie ursprünglich von mir vorgeschlagen) in die Wochen-Spalte packen würde, dann würde die Spalte wieder breiter ... 

---

Wir könnten uns noch überlegen, ob ich den Text einfach so ausgebe, wie er im Schedule steht, oder ob ich da noch was drum packe (etwa Klammern oder ein "Hinweis: wird durchgeführt von ..." oder so). Hat beides Vor- und Nachteile. Was denkst Du?

**Comment by cyildiz** [comment]
Ende der Vorlesungs-Zelle scheint die bessere Wahl.

---

Ich würde den Text in der yaml-Datei as-is ausgeben:
- Wenn man später etwas ändern möchte, müsste man sonst im "ausgelagerten" Layout etwas ändern. 
- Die gewünschte Darstellung kann sich von Kurs zu Kurs ändern, das Layout wird aber gemeinsam genutzt.
- Klammern oder ein "Hinweis:" kann man prinzipiell als "Text" einstufen und nicht als "Layout", kategorisch scheint es auch besser in die yaml-Datei zu passen.

Oder?

**Comment by cagix** [comment]
ja, wenn man das in die schedule.yaml schreibt und im shortcode nichts hinzufügt, ist man am ende flexibler. 
es ist halt im schedule.yaml mehr schreibaufwand, wenn man immer wieder die gleiche "formatierung" haben will ... 

vermutlich sollte ich das dann aber im due-date für die aufgabenblätter auch so machen. dort steht in der schedule.yaml aktuell nur das datum, und über den shortcode wird dann noch ein extra-string hinzugefügt.

**Comment by cyildiz** [comment]
hmm.. stimmt.

vielleicht noch eine überlegung: wenn man alle inhalte übersetzen müsste, welches wäre sinnvoller?

**Comment by cagix** [comment]
gute frage. ich schätze, dass es dann wie bei den anderen inhalten auch den schedule n zwei sprachen geben würde ...

**Comment by cyildiz** [comment]
ich bin mal den code durchgegangen. 
ich hatte den eindruck, dass man das layout-submodule relativ einfach sprach-neutral gestalten könnte.
denkst du, dass sich der aufwand lohnen würde?
einige tabellen-header u.ä. müsste man in die yaml-dateien verlagern.
kann nicht einschätzen, wie sinvoll das wäre...

**Comment by cagix** [comment]
Hmmm. Bei den inhaltlichen Dateien (also die "pages" für die Vorlesungen) wird je eine Version angelegt mit einem Zusatz "_de" oder "_en". Ich glaube, das wäre auch für den Schedule das beste, dann wäre es einheitlich.

**Comment by cyildiz** [comment]
Du meinst die schedule.html Datei, oder?

**Comment by cagix** [comment]
Ah, jetzt ... bin noch nicht richtig wach ;)

Ich meinte den `data/schedule.yaml`, den würde man dann in `data/schedule_de.yaml` und `data/schedule_en.yaml` haben. Aber Du hast komplett recht, im Shortcode stehen die Tabellenköpfe. 

Ich hatte tatsächlich wg. der "Misc"-Spalte schon probiert, ob ich dem Shortcode Parameter mitgeben kann und von dort aus die Tabellenspalten und -köpfe definiere. Das geht, aber das Problem ist, dass die Zuordnung am Ende immer passen muss (also die Parameter im Shortcode, die die Tabellenköpfe bestimmen müssen zu den Einträgen im Data-Template passen). Deshalb hatte ich die Idee wieder verworfen. 

Eine Idee wäre, das über die `config.yaml` zu definieren. Dort wird ja auch für das Menü und die Sprache (haben wir jetzt nicht, aber ich habe das in der Anleitung zum Learn-Theme gesehen) die Konfig gemacht. D.h. hier könnte man sagen, in Sprache X ist der Kopf von Spalte 1 der String "XXX", für Spalte 2 "..." und so weiter.

Die Alternative wäre, das im Data-Template mit unterzubringen. Bin aber nicht sicher, ob man die "Weeks" einfach mischen kann mit einem komplett anderen Eintrag. Vermutlich müsste man eine Variable "tableheader" und eine "weeks" definieren, und unter "weeks" kämen dann die jetztigen Einträge.

**Comment by cagix** [comment]
wochen-leader geht in die neue `misc_lecture` mit freier formatierung (siehe https://github.com/cagix/Hugo-Lecture-Layouts/issues/4#issuecomment-916108903)

**Comment by cagix** [comment]
sprache: sowohl data-template als auch shortcode in beiden sprachen, aufruf dann in der jeweils richtigen variante

**Comment by cagix** [comment]
siehe #4: den "Wochen-Leader" über den `misc_lecture` spezifizieren:

```yaml
---
- week: "KW40"
  lecture:
    - topic: "/misc/syllabus"
  misc_lecture:
    - notes: "Durchgeführt von **Canan**"
  misc_column:
    - notes: "Coden mit Edmonton"
---
```
