### ISSUE TITLE
Fahrplan/Schedule: Übung-Spaltenbreite reduzieren

### ISSUE THREAD

**Issue by cyildiz** [cagix/Hugo-Lecture-Layouts#6]
Zeilenumbruch zwischen Übungsblatt und (Abgabe xx); dadurch wird die Spalte schmaler.

**Comment by cagix** [comment]
@cyildiz Soll ich lieber ein `<p>` nehmen oder einfach ein `<br>`?

**Comment by cyildiz** [comment]
Ich würde sagen <br>.

**Comment by cagix** [comment]
closed by 717f417
